-- Migration 004: Candidate Intelligence, BYOK Credentials, AI Usage, Learning Engine
-- Apply this in Supabase SQL editor after migrations 001–003.
-- Tables: competency_scores, misconceptions, question_bank,
--         ai_credentials, ai_usage, learning_events

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. competency_scores
--    One row per (user, domain, competency). Upserted after every evaluation.
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists competency_scores (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users on delete cascade not null,
  domain          text not null check (domain in ('technical', 'hr', 'project')),
  competency      text not null check (char_length(competency) <= 100),
  attempts        integer not null default 0 check (attempts >= 0),
  correct_weighted numeric(6,2) not null default 0 check (correct_weighted >= 0),
  last_score      integer check (last_score between 0 and 100),
  -- rolling average of last 3 scores stored as jsonb array for consistency calc
  recent_scores   jsonb not null default '[]'::jsonb,
  mastery_level   text not null default 'weak'
                  check (mastery_level in ('weak','developing','competent','strong','mastered')),
  updated_at      timestamptz not null default now()
);

create unique index if not exists competency_scores_user_domain_comp_idx
  on competency_scores (user_id, domain, competency);

create index if not exists competency_scores_user_domain_idx
  on competency_scores (user_id, domain);

create index if not exists competency_scores_mastery_idx
  on competency_scores (user_id, mastery_level);

alter table competency_scores enable row level security;

create policy "users can read own competency scores"
  on competency_scores for select
  using (auth.uid() = user_id);

create policy "users can insert own competency scores"
  on competency_scores for insert
  with check (auth.uid() = user_id);

create policy "users can update own competency scores"
  on competency_scores for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. misconceptions
--    Detected incorrect beliefs. Resolved only when subsequent answers
--    demonstrate correction (not auto-deleted).
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists misconceptions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users on delete cascade not null,
  domain          text not null check (domain in ('technical', 'hr', 'project')),
  competency      text not null check (char_length(competency) <= 100),
  description     text not null check (char_length(description) <= 500),
  -- Example: "believes HashMap is thread-safe"
  incorrect_belief text not null check (char_length(incorrect_belief) <= 300),
  correction      text not null check (char_length(correction) <= 500),
  question_id     uuid,  -- FK to question_bank (nullable — question may be ephemeral)
  session_id      uuid references interview_sessions on delete set null,
  resolved        boolean not null default false,
  resolved_at     timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists misconceptions_user_resolved_idx
  on misconceptions (user_id, resolved);

create index if not exists misconceptions_user_domain_idx
  on misconceptions (user_id, domain);

alter table misconceptions enable row level security;

create policy "users can read own misconceptions"
  on misconceptions for select
  using (auth.uid() = user_id);

create policy "users can insert own misconceptions"
  on misconceptions for insert
  with check (auth.uid() = user_id);

create policy "users can update own misconceptions"
  on misconceptions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. question_bank
--    Global table — questions with blueprints generated by the question engine.
--    No user_id — this is a shared question store.
--    Write access: service-role only (no user INSERT policy).
--    Read access: any authenticated user (for session reconstruction).
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists question_bank (
  id                  uuid primary key default gen_random_uuid(),
  domain              text not null check (domain in ('technical', 'hr', 'project')),
  category            text not null check (char_length(category) <= 100),
  subtopic            text not null check (char_length(subtopic) <= 100),
  difficulty          text not null
                      check (difficulty in ('easy','medium','hard','scenario','architecture')),
  question_type       text not null
                      check (question_type in (
                        'conceptual','scenario','debugging','coding',
                        'system_design','trade_off','security','performance'
                      )),
  question_text       text not null check (char_length(question_text) <= 2000),
  expected_concepts   jsonb not null default '[]'::jsonb,  -- string[]
  common_mistakes     jsonb not null default '[]'::jsonb,  -- string[]
  rubric              jsonb not null default '[]'::jsonb,  -- { concept, weight }[]
  source_evidence     jsonb not null default '[]'::jsonb,  -- { file, snippet }[] for project Qs
  model_version       text not null check (char_length(model_version) <= 50),
  prompt_version      text not null check (char_length(prompt_version) <= 50),
  created_at          timestamptz not null default now()
);

create index if not exists question_bank_domain_subtopic_idx
  on question_bank (domain, subtopic);

create index if not exists question_bank_domain_difficulty_idx
  on question_bank (domain, difficulty);

alter table question_bank enable row level security;

-- Authenticated users can read questions (for session replay / coaching)
create policy "authenticated users can read question bank"
  on question_bank for select
  using (auth.role() = 'authenticated');

-- NO insert/update/delete policy for regular users — service-role only

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. ai_credentials
--    BYOK encrypted credentials. Never stores plaintext secrets.
--    encrypted_secret contains AES-256-GCM ciphertext (JSON: { iv, tag, data }).
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists ai_credentials (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid references auth.users on delete cascade not null,
  provider          text not null check (provider in ('gemini', 'openai', 'anthropic')),
  encrypted_secret  text not null,  -- AES-256-GCM ciphertext; NEVER plaintext
  key_last4         text not null check (char_length(key_last4) = 4),
  status            text not null default 'valid'
                    check (status in ('valid', 'invalid', 'untested')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  last_verified_at  timestamptz
);

create unique index if not exists ai_credentials_user_provider_idx
  on ai_credentials (user_id, provider);

alter table ai_credentials enable row level security;

-- Users can see their own credentials (excluding encrypted_secret — enforced at API layer)
create policy "users can read own ai credentials"
  on ai_credentials for select
  using (auth.uid() = user_id);

create policy "users can insert own ai credentials"
  on ai_credentials for insert
  with check (auth.uid() = user_id);

create policy "users can update own ai credentials"
  on ai_credentials for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users can delete own ai credentials"
  on ai_credentials for delete
  using (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. ai_usage
--    Tracks every AI provider call: tokens, latency, cost, operation.
--    Used for quota enforcement, cost tracking, and observability.
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists ai_usage (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid references auth.users on delete cascade not null,
  provider            text not null check (provider in ('gemini', 'openai', 'anthropic')),
  model               text not null check (char_length(model) <= 100),
  operation           text not null check (char_length(operation) <= 100),
  -- e.g. "quiz/generate", "interview/question", "interview/evaluate"
  is_byok             boolean not null default false,
  input_tokens        integer check (input_tokens >= 0),
  output_tokens       integer check (output_tokens >= 0),
  latency_ms          integer check (latency_ms >= 0),
  estimated_cost_usd  numeric(10,6) check (estimated_cost_usd >= 0),
  success             boolean not null default true,
  error_code          text,
  created_at          timestamptz not null default now()
);

create index if not exists ai_usage_user_created_idx
  on ai_usage (user_id, created_at desc);

create index if not exists ai_usage_user_operation_idx
  on ai_usage (user_id, operation);

alter table ai_usage enable row level security;

create policy "users can read own ai usage"
  on ai_usage for select
  using (auth.uid() = user_id);

create policy "users can insert own ai usage"
  on ai_usage for insert
  with check (auth.uid() = user_id);

-- No update or delete — usage is an immutable audit log

-- ──────────────────────────────────────────────────────────────────────────────
-- 6. learning_events
--    Immutable event log of every question-answer-evaluation cycle.
--    Used for analytics, mastery calculation, and learning loop.
-- ──────────────────────────────────────────────────────────────────────────────

create table if not exists learning_events (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users on delete cascade not null,
  session_id      uuid references interview_sessions on delete set null,
  question_id     uuid,  -- FK to question_bank (nullable)
  domain          text not null check (domain in ('technical', 'hr', 'project')),
  competency      text not null check (char_length(competency) <= 100),
  difficulty      text not null
                  check (difficulty in ('easy','medium','hard','scenario','architecture')),
  score           integer not null check (score between 0 and 100),
  event_type      text not null
                  check (event_type in (
                    'first_attempt','retry','misconception_detected',
                    'misconception_resolved','mastery_achieved'
                  )),
  created_at      timestamptz not null default now()
);

create index if not exists learning_events_user_created_idx
  on learning_events (user_id, created_at desc);

create index if not exists learning_events_user_competency_idx
  on learning_events (user_id, competency);

alter table learning_events enable row level security;

create policy "users can read own learning events"
  on learning_events for select
  using (auth.uid() = user_id);

create policy "users can insert own learning events"
  on learning_events for insert
  with check (auth.uid() = user_id);

-- No update or delete — learning events are an immutable audit log

-- ──────────────────────────────────────────────────────────────────────────────
-- 7. CASCADE Retrofit for Migrations 001–003 (Phase 16 Hardening)
--    Ensures DELETE /api/account cleanly cascades across all tables without FK errors.
-- ──────────────────────────────────────────────────────────────────────────────

do $$
begin
  -- quiz_attempts user_id CASCADE
  if exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'quiz_attempts_user_id_fkey'
  ) then
    alter table quiz_attempts drop constraint quiz_attempts_user_id_fkey;
    alter table quiz_attempts
      add constraint quiz_attempts_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;

  -- interview_sessions user_id CASCADE
  if exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'interview_sessions_user_id_fkey'
  ) then
    alter table interview_sessions drop constraint interview_sessions_user_id_fkey;
    alter table interview_sessions
      add constraint interview_sessions_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;

  -- resumes user_id CASCADE
  if exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'resumes_user_id_fkey'
  ) then
    alter table resumes drop constraint resumes_user_id_fkey;
    alter table resumes
      add constraint resumes_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;
end $$;
